### PR TITLE
added server function

### PR DESCRIPTION
**Pull request by katajello**
need to NPM install still

### CODE REVIEW

**Comment by jjkeith** [comment]
Looks good, @katajello . Can you change
`mongoose = require('mongoose'),`
to
`elephant = require('elephant')`?

**Comment by katajello** [comment]
THAT MAKES NO SENSE!!

**Comment by jjkeith** [comment]
DO IT ANYWAY OR YOU'RE FIRED!

**Comment by jjkeith** [comment]
Looks good. Elephants are better, @katajello

**Pull request merged**
